/* Generated by re2c 2.1.1 on Sun Mar 13 22:59:25 2022 */
#include <cstdint>
#include <cuchar>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <variant>

#include "lexer_defs.h"
#include "lexer.h"

namespace Lexer {

std::optional<Token> lex(LexerState& state)
{
    const char* const base { state.base };
    const char* const limit { state.limit };

    auto& cursor { state.cursor };
    const char* marker {};
    const char* ctxmarker {};

    for (;;) {
        const char* const begin_cursor { state.cursor };
        const size_t begin_offset { state.cursor - state.base };

        
{
	char yych;
	unsigned int yyaccept = 0;
	if (limit - cursor < 14) true;
	yych = *cursor;
	switch (yych) {
	case '\t' ... '\r':
	case ' ': goto yy4;
	case '"': goto yy7;
	case '&': goto yy8;
	case '\'': goto yy10;
	case '(': goto yy12;
	case ')': goto yy14;
	case '*': goto yy16;
	case '+': goto yy18;
	case ',': goto yy20;
	case '-': goto yy22;
	case '.': goto yy24;
	case '/': goto yy26;
	case '0' ... '9': goto yy28;
	case ':': goto yy31;
	case ';': goto yy33;
	case '<': goto yy35;
	case '=': goto yy37;
	case '>': goto yy39;
	case 'A':
	case 'a': goto yy41;
	case 'B':
	case 'b': goto yy43;
	case 'C':
	case 'c': goto yy44;
	case 'D':
	case 'd': goto yy45;
	case 'E':
	case 'e': goto yy46;
	case 'F':
	case 'f': goto yy47;
	case 'G':
	case 'g': goto yy48;
	case 'H':
	case 'J' ... 'K':
	case 'Q':
	case 'Y' ... 'Z':
	case 'h':
	case 'j' ... 'k':
	case 'q':
	case 'y' ... 'z': goto yy49;
	case 'I':
	case 'i': goto yy51;
	case 'L':
	case 'l': goto yy52;
	case 'M':
	case 'm': goto yy53;
	case 'N':
	case 'n': goto yy54;
	case 'O':
	case 'o': goto yy55;
	case 'P':
	case 'p': goto yy56;
	case 'R':
	case 'r': goto yy57;
	case 'S':
	case 's': goto yy58;
	case 'T':
	case 't': goto yy59;
	case 'U':
	case 'u': goto yy60;
	case 'V':
	case 'v': goto yy61;
	case 'W':
	case 'w': goto yy62;
	case 'X':
	case 'x': goto yy63;
	case '[': goto yy64;
	case '\\': goto yy66;
	case ']': goto yy67;
	case '|': goto yy69;
	default: goto yy2;
	}
yy2:
	++cursor;
yy3:
	{ return std::nullopt; }
yy4:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '\t' ... '\r':
	case ' ': goto yy4;
	default: goto yy6;
	}
yy6:
	{ continue; }
yy7:
	yyaccept = 0;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '\n': goto yy3;
	default: goto yy72;
	}
yy8:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::AMPERSAND }; }
yy10:
	yyaccept = 1;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '\n': goto yy11;
	default: goto yy77;
	}
yy11:
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::APOSTROPHE }; }
yy12:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::LEFT_PAREN }; }
yy14:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::RIGHT_PAREN }; }
yy16:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '*': goto yy78;
	default: goto yy17;
	}
yy17:
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::ASTERISK }; }
yy18:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::PLUS_SIGN }; }
yy20:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::COMMA }; }
yy22:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '-': goto yy80;
	default: goto yy23;
	}
yy23:
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::HYPHEN }; }
yy24:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::DOT }; }
yy26:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '=': goto yy83;
	default: goto yy27;
	}
yy27:
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::SLASH }; }
yy28:
	yyaccept = 2;
	++cursor;
	marker = cursor;
	if (limit - cursor < 2) true;
	yych = *cursor;
	switch (yych) {
	case '#': goto yy85;
	case '.': goto yy86;
	case '0' ... '9': goto yy28;
	case 'E':
	case 'e': goto yy87;
	case '_': goto yy88;
	default: goto yy30;
	}
yy30:
	{ return DecimalLiteral { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, 0 }; }
yy31:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '=': goto yy89;
	default: goto yy32;
	}
yy32:
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::COLON }; }
yy33:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::SEMICOLON }; }
yy35:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '=': goto yy91;
	case '>': goto yy93;
	default: goto yy36;
	}
yy36:
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::LESS_THAN_SIGN }; }
yy37:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '>': goto yy95;
	default: goto yy38;
	}
yy38:
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::EQUALS_SIGN }; }
yy39:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '=': goto yy97;
	default: goto yy40;
	}
yy40:
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::GREATER_THAN_SIGN }; }
yy41:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'B':
	case 'b': goto yy99;
	case 'C':
	case 'c': goto yy100;
	case 'F':
	case 'f': goto yy101;
	case 'L':
	case 'l': goto yy102;
	case 'N':
	case 'n': goto yy103;
	case 'R':
	case 'r': goto yy104;
	case 'S':
	case 's': goto yy105;
	default: goto yy50;
	}
yy42:
	{ return BasicIdentifier { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, "" }; }
yy43:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '"': goto yy107;
	case 'E':
	case 'e': goto yy108;
	case 'L':
	case 'l': goto yy109;
	case 'O':
	case 'o': goto yy110;
	case 'U':
	case 'u': goto yy111;
	default: goto yy50;
	}
yy44:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy112;
	case 'O':
	case 'o': goto yy113;
	default: goto yy50;
	}
yy45:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy114;
	case 'O':
	case 'o': goto yy115;
	default: goto yy50;
	}
yy46:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy116;
	case 'N':
	case 'n': goto yy117;
	case 'X':
	case 'x': goto yy118;
	default: goto yy50;
	}
yy47:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy119;
	case 'O':
	case 'o': goto yy120;
	case 'U':
	case 'u': goto yy121;
	default: goto yy50;
	}
yy48:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy122;
	case 'R':
	case 'r': goto yy123;
	case 'U':
	case 'u': goto yy124;
	default: goto yy50;
	}
yy49:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
yy50:
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy42;
	}
yy51:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'F':
	case 'f': goto yy125;
	case 'M':
	case 'm': goto yy127;
	case 'N':
	case 'n': goto yy128;
	case 'S':
	case 's': goto yy130;
	default: goto yy50;
	}
yy52:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy132;
	case 'I':
	case 'i': goto yy133;
	case 'O':
	case 'o': goto yy134;
	default: goto yy50;
	}
yy53:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy135;
	case 'O':
	case 'o': goto yy136;
	default: goto yy50;
	}
yy54:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy137;
	case 'E':
	case 'e': goto yy138;
	case 'O':
	case 'o': goto yy139;
	case 'U':
	case 'u': goto yy140;
	default: goto yy50;
	}
yy55:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '"': goto yy107;
	case 'F':
	case 'f': goto yy141;
	case 'N':
	case 'n': goto yy143;
	case 'P':
	case 'p': goto yy145;
	case 'R':
	case 'r': goto yy146;
	case 'T':
	case 't': goto yy148;
	case 'U':
	case 'u': goto yy149;
	default: goto yy50;
	}
yy56:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy150;
	case 'O':
	case 'o': goto yy151;
	case 'R':
	case 'r': goto yy152;
	case 'U':
	case 'u': goto yy153;
	default: goto yy50;
	}
yy57:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy154;
	case 'E':
	case 'e': goto yy155;
	case 'O':
	case 'o': goto yy156;
	default: goto yy50;
	}
yy58:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy157;
	case 'H':
	case 'h': goto yy158;
	case 'I':
	case 'i': goto yy159;
	case 'L':
	case 'l': goto yy160;
	case 'R':
	case 'r': goto yy161;
	case 'U':
	case 'u': goto yy162;
	default: goto yy50;
	}
yy59:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'H':
	case 'h': goto yy163;
	case 'O':
	case 'o': goto yy164;
	case 'R':
	case 'r': goto yy166;
	case 'Y':
	case 'y': goto yy167;
	default: goto yy50;
	}
yy60:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy168;
	case 'S':
	case 's': goto yy169;
	default: goto yy50;
	}
yy61:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy170;
	default: goto yy50;
	}
yy62:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy171;
	case 'H':
	case 'h': goto yy172;
	case 'I':
	case 'i': goto yy173;
	default: goto yy50;
	}
yy63:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '"': goto yy107;
	case 'N':
	case 'n': goto yy174;
	case 'O':
	case 'o': goto yy175;
	default: goto yy50;
	}
yy64:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::LEFT_SQUARE_BRACKET }; }
yy66:
	yyaccept = 0;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '\n': goto yy3;
	default: goto yy176;
	}
yy67:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::RIGHT_SQUARE_BRACKET }; }
yy69:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::VERTICAL_LINE }; }
yy71:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
yy72:
	switch (yych) {
	case '\n': goto yy73;
	case '"': goto yy74;
	default: goto yy71;
	}
yy73:
	cursor = marker;
	switch (yyaccept) {
	case 0:
		goto yy3;
	case 1:
		goto yy11;
	case 2:
		goto yy30;
	case 3:
		goto yy42;
	case 4:
		goto yy76;
	case 5:
		goto yy126;
	case 6:
		goto yy129;
	case 7:
		goto yy131;
	case 8:
		goto yy142;
	case 9:
		goto yy144;
	case 10:
		goto yy147;
	case 11:
		goto yy165;
	case 12:
		goto yy188;
	case 13:
		goto yy193;
	case 14:
		goto yy195;
	case 15:
		goto yy208;
	case 16:
		goto yy216;
	case 17:
		goto yy221;
	case 18:
		goto yy235;
	case 19:
		goto yy237;
	case 20:
		goto yy240;
	case 21:
		goto yy243;
	case 22:
		goto yy245;
	case 23:
		goto yy250;
	case 24:
		goto yy262;
	case 25:
		goto yy266;
	case 26:
		goto yy268;
	case 27:
		goto yy274;
	case 28:
		goto yy276;
	case 29:
		goto yy278;
	case 30:
		goto yy280;
	case 31:
		goto yy289;
	case 32:
		goto yy297;
	case 33:
		goto yy300;
	case 34:
		goto yy302;
	case 35:
		goto yy314;
	case 36:
		goto yy317;
	case 37:
		goto yy324;
	case 38:
		goto yy328;
	case 39:
		goto yy330;
	case 40:
		goto yy343;
	case 41:
		goto yy345;
	case 42:
		goto yy347;
	case 43:
		goto yy349;
	case 44:
		goto yy351;
	case 45:
		goto yy355;
	case 46:
		goto yy360;
	case 47:
		goto yy374;
	case 48:
		goto yy377;
	case 49:
		goto yy383;
	case 50:
		goto yy385;
	case 51:
		goto yy388;
	case 52:
		goto yy390;
	case 53:
		goto yy396;
	case 54:
		goto yy398;
	case 55:
		goto yy401;
	case 56:
		goto yy404;
	case 57:
		goto yy406;
	case 58:
		goto yy414;
	case 59:
		goto yy419;
	case 60:
		goto yy424;
	case 61:
		goto yy426;
	case 62:
		goto yy436;
	case 63:
		goto yy451;
	case 64:
		goto yy453;
	case 65:
		goto yy456;
	case 66:
		goto yy461;
	case 67:
		goto yy464;
	case 68:
		goto yy466;
	case 69:
		goto yy472;
	case 70:
		goto yy474;
	case 71:
		goto yy480;
	case 72:
		goto yy486;
	case 73:
		goto yy493;
	case 74:
		goto yy497;
	case 75:
		goto yy499;
	case 76:
		goto yy501;
	case 77:
		goto yy503;
	case 78:
		goto yy506;
	case 79:
		goto yy508;
	case 80:
		goto yy521;
	case 81:
		goto yy523;
	case 82:
		goto yy526;
	case 83:
		goto yy528;
	case 84:
		goto yy530;
	case 85:
		goto yy532;
	case 86:
		goto yy536;
	case 87:
		goto yy542;
	case 88:
		goto yy550;
	case 89:
		goto yy553;
	case 90:
		goto yy555;
	case 91:
		goto yy557;
	case 92:
		goto yy563;
	case 93:
		goto yy565;
	case 94:
		goto yy569;
	case 95:
		goto yy572;
	case 96:
		goto yy576;
	case 97:
		goto yy579;
	case 98:
		goto yy581;
	case 99:
		goto yy583;
	case 100:
		goto yy585;
	case 101:
		goto yy590;
	case 102:
		goto yy592;
	case 103:
		goto yy594;
	case 104:
		goto yy598;
	default:
		goto yy601;
	}
yy74:
	yyaccept = 4;
	++cursor;
	marker = cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '\n': goto yy76;
	case '"': goto yy74;
	default: goto yy71;
	}
yy76:
	{ return StringLiteral { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, "" }; }
yy77:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '\'': goto yy178;
	default: goto yy73;
	}
yy78:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::DOUBLE_STAR }; }
yy80:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '\n': goto yy82;
	default: goto yy80;
	}
yy82:
	{ return Comment { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, "" }; }
yy83:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::INEQUALITY }; }
yy85:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'F':
	case 'a' ... 'f': goto yy180;
	default: goto yy73;
	}
yy86:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9': goto yy182;
	default: goto yy73;
	}
yy87:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '+':
	case '-': goto yy184;
	case '0' ... '9': goto yy185;
	default: goto yy73;
	}
yy88:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9': goto yy28;
	default: goto yy73;
	}
yy89:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::VAR_ASSIGNMENT }; }
yy91:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::LT_OR_EQUAL }; }
yy93:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::BOX }; }
yy95:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::ARROW }; }
yy97:
	++cursor;
	{ return Delimiter { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, DelimiterKind::GT_OR_EQUAL }; }
yy99:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy187;
	default: goto yy50;
	}
yy100:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy189;
	default: goto yy50;
	}
yy101:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy190;
	default: goto yy50;
	}
yy102:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy191;
	case 'L':
	case 'l': goto yy192;
	default: goto yy50;
	}
yy103:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy194;
	default: goto yy50;
	}
yy104:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy196;
	case 'R':
	case 'r': goto yy197;
	default: goto yy50;
	}
yy105:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy198;
	default: goto yy50;
	}
yy106:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	default: goto yy73;
	}
yy107:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '_': goto yy73;
	default: goto yy202;
	}
yy108:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'G':
	case 'g': goto yy203;
	default: goto yy50;
	}
yy109:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy204;
	default: goto yy50;
	}
yy110:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy205;
	default: goto yy50;
	}
yy111:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'F':
	case 'f': goto yy206;
	case 'S':
	case 's': goto yy207;
	default: goto yy50;
	}
yy112:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy209;
	default: goto yy50;
	}
yy113:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'M':
	case 'm': goto yy210;
	case 'N':
	case 'n': goto yy211;
	default: goto yy50;
	}
yy114:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy212;
	default: goto yy50;
	}
yy115:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'W':
	case 'w': goto yy213;
	default: goto yy50;
	}
yy116:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy214;
	default: goto yy50;
	}
yy117:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy215;
	case 'T':
	case 't': goto yy217;
	default: goto yy50;
	}
yy118:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy218;
	default: goto yy50;
	}
yy119:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy219;
	default: goto yy50;
	}
yy120:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy220;
	default: goto yy50;
	}
yy121:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy222;
	default: goto yy50;
	}
yy122:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy223;
	default: goto yy50;
	}
yy123:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy224;
	default: goto yy50;
	}
yy124:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy225;
	default: goto yy50;
	}
yy125:
	yyaccept = 5;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy126;
	}
yy126:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::IF }; }
yy127:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'P':
	case 'p': goto yy226;
	default: goto yy50;
	}
yy128:
	yyaccept = 6;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'D':
	case 'F' ... 'N':
	case 'P' ... 'Z':
	case 'a' ... 'd':
	case 'f' ... 'n':
	case 'p' ... 'z': goto yy49;
	case 'E':
	case 'e': goto yy227;
	case 'O':
	case 'o': goto yy228;
	case '_': goto yy106;
	default: goto yy129;
	}
yy129:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::IN }; }
yy130:
	yyaccept = 7;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy131;
	}
yy131:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::IS }; }
yy132:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'B':
	case 'b': goto yy229;
	default: goto yy50;
	}
yy133:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'B':
	case 'b': goto yy230;
	case 'N':
	case 'n': goto yy231;
	case 'T':
	case 't': goto yy232;
	default: goto yy50;
	}
yy134:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy233;
	default: goto yy50;
	}
yy135:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'P':
	case 'p': goto yy234;
	default: goto yy50;
	}
yy136:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy236;
	default: goto yy50;
	}
yy137:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy238;
	default: goto yy50;
	}
yy138:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'W':
	case 'w': goto yy239;
	case 'X':
	case 'x': goto yy241;
	default: goto yy50;
	}
yy139:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy242;
	case 'T':
	case 't': goto yy244;
	default: goto yy50;
	}
yy140:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy246;
	default: goto yy50;
	}
yy141:
	yyaccept = 8;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy142;
	}
yy142:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::OF }; }
yy143:
	yyaccept = 9;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy144;
	}
yy144:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ON }; }
yy145:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy247;
	default: goto yy50;
	}
yy146:
	yyaccept = 10;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy147;
	}
yy147:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::OR }; }
yy148:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'H':
	case 'h': goto yy248;
	default: goto yy50;
	}
yy149:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy249;
	default: goto yy50;
	}
yy150:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy251;
	default: goto yy50;
	}
yy151:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy252;
	case 'S':
	case 's': goto yy253;
	default: goto yy50;
	}
yy152:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy254;
	default: goto yy50;
	}
yy153:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy255;
	default: goto yy50;
	}
yy154:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy256;
	default: goto yy50;
	}
yy155:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy257;
	case 'F':
	case 'f': goto yy258;
	case 'G':
	case 'g': goto yy259;
	case 'J':
	case 'j': goto yy260;
	case 'M':
	case 'm': goto yy261;
	case 'P':
	case 'p': goto yy263;
	case 'T':
	case 't': goto yy264;
	default: goto yy50;
	}
yy156:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy265;
	case 'R':
	case 'r': goto yy267;
	default: goto yy50;
	}
yy157:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy269;
	case 'V':
	case 'v': goto yy270;
	default: goto yy50;
	}
yy158:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy271;
	default: goto yy50;
	}
yy159:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'G':
	case 'g': goto yy272;
	default: goto yy50;
	}
yy160:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy273;
	case 'L':
	case 'l': goto yy275;
	default: goto yy50;
	}
yy161:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy277;
	case 'L':
	case 'l': goto yy279;
	default: goto yy50;
	}
yy162:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'B':
	case 'b': goto yy281;
	default: goto yy50;
	}
yy163:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy282;
	default: goto yy50;
	}
yy164:
	yyaccept = 11;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy165;
	}
yy165:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::TO }; }
yy166:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy283;
	default: goto yy50;
	}
yy167:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'P':
	case 'p': goto yy284;
	default: goto yy50;
	}
yy168:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy285;
	case 'I':
	case 'i': goto yy286;
	case 'T':
	case 't': goto yy287;
	default: goto yy50;
	}
yy169:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy288;
	default: goto yy50;
	}
yy170:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy290;
	default: goto yy50;
	}
yy171:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy291;
	default: goto yy50;
	}
yy172:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy292;
	case 'I':
	case 'i': goto yy293;
	default: goto yy50;
	}
yy173:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy294;
	default: goto yy50;
	}
yy174:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy295;
	default: goto yy50;
	}
yy175:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy296;
	default: goto yy50;
	}
yy176:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '\n': goto yy73;
	case '\\': goto yy298;
	default: goto yy176;
	}
yy178:
	++cursor;
	{ return CharacterLiteral { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, 'a' }; }
yy180:
	++cursor;
	if (limit - cursor < 3) true;
	yych = *cursor;
	switch (yych) {
	case '#': goto yy301;
	case '.': goto yy303;
	case '0' ... '9':
	case 'A' ... 'F':
	case 'a' ... 'f': goto yy180;
	case '_': goto yy85;
	default: goto yy73;
	}
yy182:
	yyaccept = 2;
	++cursor;
	marker = cursor;
	if (limit - cursor < 2) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9': goto yy182;
	case 'E':
	case 'e': goto yy87;
	case '_': goto yy86;
	default: goto yy30;
	}
yy184:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9': goto yy185;
	default: goto yy73;
	}
yy185:
	yyaccept = 2;
	++cursor;
	marker = cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9': goto yy185;
	case '_': goto yy184;
	default: goto yy30;
	}
yy187:
	yyaccept = 12;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy188;
	}
yy188:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ABS }; }
yy189:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy304;
	default: goto yy50;
	}
yy190:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy305;
	default: goto yy50;
	}
yy191:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy306;
	default: goto yy50;
	}
yy192:
	yyaccept = 13;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy193;
	}
yy193:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ALL }; }
yy194:
	yyaccept = 14;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy195;
	}
yy195:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::AND }; }
yy196:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'H':
	case 'h': goto yy307;
	default: goto yy50;
	}
yy197:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy308;
	default: goto yy50;
	}
yy198:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy309;
	default: goto yy50;
	}
yy199:
	++cursor;
	{ return BitStringLiteral { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, BitStringBase::BINARY, "" }; }
yy201:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
yy202:
	switch (yych) {
	case '"': goto yy199;
	case '0' ... '9':
	case 'A' ... 'F':
	case 'a' ... 'f': goto yy201;
	case '_': goto yy310;
	default: goto yy73;
	}
yy203:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy311;
	default: goto yy50;
	}
yy204:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy312;
	default: goto yy50;
	}
yy205:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'Y':
	case 'y': goto yy313;
	default: goto yy50;
	}
yy206:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'F':
	case 'f': goto yy315;
	default: goto yy50;
	}
yy207:
	yyaccept = 15;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy208;
	}
yy208:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::BUS }; }
yy209:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy316;
	default: goto yy50;
	}
yy210:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'P':
	case 'p': goto yy318;
	default: goto yy50;
	}
yy211:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'F':
	case 'f': goto yy319;
	case 'S':
	case 's': goto yy320;
	default: goto yy50;
	}
yy212:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy321;
	default: goto yy50;
	}
yy213:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy322;
	default: goto yy50;
	}
yy214:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy323;
	case 'I':
	case 'i': goto yy325;
	default: goto yy50;
	}
yy215:
	yyaccept = 16;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy216;
	}
yy216:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::END }; }
yy217:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy326;
	default: goto yy50;
	}
yy218:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy327;
	default: goto yy50;
	}
yy219:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy329;
	default: goto yy50;
	}
yy220:
	yyaccept = 17;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy221;
	}
yy221:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::FOR }; }
yy222:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy331;
	default: goto yy50;
	}
yy223:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy332;
	default: goto yy50;
	}
yy224:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'U':
	case 'u': goto yy333;
	default: goto yy50;
	}
yy225:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy334;
	default: goto yy50;
	}
yy226:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'U':
	case 'u': goto yy335;
	default: goto yy50;
	}
yy227:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy336;
	default: goto yy50;
	}
yy228:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'U':
	case 'u': goto yy337;
	default: goto yy50;
	}
yy229:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy338;
	default: goto yy50;
	}
yy230:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy339;
	default: goto yy50;
	}
yy231:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'K':
	case 'k': goto yy340;
	default: goto yy50;
	}
yy232:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy341;
	default: goto yy50;
	}
yy233:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'P':
	case 'p': goto yy342;
	default: goto yy50;
	}
yy234:
	yyaccept = 18;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy235;
	}
yy235:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::MAP }; }
yy236:
	yyaccept = 19;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy237;
	}
yy237:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::MOD }; }
yy238:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy344;
	default: goto yy50;
	}
yy239:
	yyaccept = 20;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy240;
	}
yy240:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::NEW }; }
yy241:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy346;
	default: goto yy50;
	}
yy242:
	yyaccept = 21;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy243;
	}
yy243:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::NOR }; }
yy244:
	yyaccept = 22;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy245;
	}
yy245:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::NOT }; }
yy246:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy348;
	default: goto yy50;
	}
yy247:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy350;
	default: goto yy50;
	}
yy248:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy352;
	default: goto yy50;
	}
yy249:
	yyaccept = 23;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy250;
	}
yy250:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::OUT }; }
yy251:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'K':
	case 'k': goto yy353;
	default: goto yy50;
	}
yy252:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy354;
	default: goto yy50;
	}
yy253:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy356;
	default: goto yy50;
	}
yy254:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy357;
	case 'T':
	case 't': goto yy358;
	default: goto yy50;
	}
yy255:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy359;
	default: goto yy50;
	}
yy256:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'G':
	case 'g': goto yy361;
	default: goto yy50;
	}
yy257:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy362;
	default: goto yy50;
	}
yy258:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy363;
	default: goto yy50;
	}
yy259:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy364;
	default: goto yy50;
	}
yy260:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy365;
	default: goto yy50;
	}
yy261:
	yyaccept = 24;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy262;
	}
yy262:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::REM }; }
yy263:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy366;
	default: goto yy50;
	}
yy264:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'U':
	case 'u': goto yy367;
	default: goto yy50;
	}
yy265:
	yyaccept = 25;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy266;
	}
yy266:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ROL }; }
yy267:
	yyaccept = 26;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy268;
	}
yy268:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ROR }; }
yy269:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy368;
	default: goto yy50;
	}
yy270:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy369;
	default: goto yy50;
	}
yy271:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy370;
	default: goto yy50;
	}
yy272:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy371;
	default: goto yy50;
	}
yy273:
	yyaccept = 27;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy274;
	}
yy274:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::SLA }; }
yy275:
	yyaccept = 28;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy276;
	}
yy276:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::SLL }; }
yy277:
	yyaccept = 29;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy278;
	}
yy278:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::SRA }; }
yy279:
	yyaccept = 30;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy280;
	}
yy280:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::SRL }; }
yy281:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy372;
	default: goto yy50;
	}
yy282:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy373;
	default: goto yy50;
	}
yy283:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy375;
	default: goto yy50;
	}
yy284:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy376;
	default: goto yy50;
	}
yy285:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'F':
	case 'f': goto yy378;
	default: goto yy50;
	}
yy286:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy379;
	default: goto yy50;
	}
yy287:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy380;
	default: goto yy50;
	}
yy288:
	yyaccept = 31;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy289;
	}
yy289:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::USE }; }
yy290:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy381;
	default: goto yy50;
	}
yy291:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy382;
	default: goto yy50;
	}
yy292:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy384;
	default: goto yy50;
	}
yy293:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy386;
	default: goto yy50;
	}
yy294:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'H':
	case 'h': goto yy387;
	default: goto yy50;
	}
yy295:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy389;
	default: goto yy50;
	}
yy296:
	yyaccept = 32;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy297;
	}
yy297:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::XOR }; }
yy298:
	yyaccept = 33;
	++cursor;
	marker = cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '\n': goto yy300;
	case '\\': goto yy298;
	default: goto yy176;
	}
yy300:
	{ return ExtendedIdentifier { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, "" }; }
yy301:
	yyaccept = 34;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy391;
	default: goto yy302;
	}
yy302:
	{ return BasedLiteral { begin_offset, std::string_view {begin_cursor, cursor - begin_cursor}, 0, 0 }; }
yy303:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'F':
	case 'a' ... 'f': goto yy392;
	default: goto yy73;
	}
yy304:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy394;
	default: goto yy50;
	}
yy305:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy395;
	default: goto yy50;
	}
yy306:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy397;
	default: goto yy50;
	}
yy307:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy399;
	default: goto yy50;
	}
yy308:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'Y':
	case 'y': goto yy400;
	default: goto yy50;
	}
yy309:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy402;
	default: goto yy50;
	}
yy310:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'F':
	case 'a' ... 'f': goto yy201;
	default: goto yy73;
	}
yy311:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy403;
	default: goto yy50;
	}
yy312:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'K':
	case 'k': goto yy405;
	default: goto yy50;
	}
yy313:
	yyaccept = 35;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy314;
	}
yy314:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::BODY }; }
yy315:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy407;
	default: goto yy50;
	}
yy316:
	yyaccept = 36;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy317;
	}
yy317:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::CASE }; }
yy318:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy408;
	default: goto yy50;
	}
yy319:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy409;
	default: goto yy50;
	}
yy320:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy410;
	default: goto yy50;
	}
yy321:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy411;
	default: goto yy50;
	}
yy322:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy412;
	default: goto yy50;
	}
yy323:
	yyaccept = 37;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy324;
	}
yy324:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ELSE }; }
yy325:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'F':
	case 'f': goto yy413;
	default: goto yy50;
	}
yy326:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy415;
	default: goto yy50;
	}
yy327:
	yyaccept = 38;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy328;
	}
yy328:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::EXIT }; }
yy329:
	yyaccept = 39;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy330;
	}
yy330:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::FILE }; }
yy331:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy416;
	default: goto yy50;
	}
yy332:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy417;
	default: goto yy50;
	}
yy333:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'P':
	case 'p': goto yy418;
	default: goto yy50;
	}
yy334:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy420;
	default: goto yy50;
	}
yy335:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy421;
	default: goto yy50;
	}
yy336:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy422;
	default: goto yy50;
	}
yy337:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy423;
	default: goto yy50;
	}
yy338:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy425;
	default: goto yy50;
	}
yy339:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy427;
	default: goto yy50;
	}
yy340:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy428;
	default: goto yy50;
	}
yy341:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy429;
	default: goto yy50;
	}
yy342:
	yyaccept = 40;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy343;
	}
yy343:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::LOOP }; }
yy344:
	yyaccept = 41;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy345;
	}
yy345:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::NAND }; }
yy346:
	yyaccept = 42;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy347;
	}
yy347:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::NEXT }; }
yy348:
	yyaccept = 43;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy349;
	}
yy349:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ID_NULL }; }
yy350:
	yyaccept = 44;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy351;
	}
yy351:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::OPEN }; }
yy352:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy430;
	default: goto yy50;
	}
yy353:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy431;
	default: goto yy50;
	}
yy354:
	yyaccept = 45;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy355;
	}
yy355:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::PORT }; }
yy356:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'P':
	case 'p': goto yy432;
	default: goto yy50;
	}
yy357:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy433;
	default: goto yy50;
	}
yy358:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy434;
	default: goto yy50;
	}
yy359:
	yyaccept = 46;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy360;
	}
yy360:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::PURE }; }
yy361:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy435;
	default: goto yy50;
	}
yy362:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy437;
	default: goto yy50;
	}
yy363:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy438;
	default: goto yy50;
	}
yy364:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy439;
	default: goto yy50;
	}
yy365:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy440;
	default: goto yy50;
	}
yy366:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy441;
	default: goto yy50;
	}
yy367:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy442;
	default: goto yy50;
	}
yy368:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy443;
	default: goto yy50;
	}
yy369:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy444;
	default: goto yy50;
	}
yy370:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy445;
	default: goto yy50;
	}
yy371:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy446;
	default: goto yy50;
	}
yy372:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'Y':
	case 'y': goto yy447;
	default: goto yy50;
	}
yy373:
	yyaccept = 47;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy374;
	}
yy374:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::THEN }; }
yy375:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy448;
	default: goto yy50;
	}
yy376:
	yyaccept = 48;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy377;
	}
yy377:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::TYPE }; }
yy378:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'F':
	case 'f': goto yy449;
	default: goto yy50;
	}
yy379:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy450;
	default: goto yy50;
	}
yy380:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy452;
	default: goto yy50;
	}
yy381:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy454;
	default: goto yy50;
	}
yy382:
	yyaccept = 49;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy383;
	}
yy383:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::WAIT }; }
yy384:
	yyaccept = 50;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy385;
	}
yy385:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::WHEN }; }
yy386:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy455;
	default: goto yy50;
	}
yy387:
	yyaccept = 51;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy388;
	}
yy388:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::WITH }; }
yy389:
	yyaccept = 52;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy390;
	}
yy390:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::XNOR }; }
yy391:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '+':
	case '-': goto yy457;
	case '0' ... '9': goto yy458;
	default: goto yy73;
	}
yy392:
	++cursor;
	if (limit - cursor < 3) true;
	yych = *cursor;
	switch (yych) {
	case '#': goto yy301;
	case '0' ... '9':
	case 'A' ... 'F':
	case 'a' ... 'f': goto yy392;
	case '_': goto yy303;
	default: goto yy73;
	}
yy394:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy460;
	default: goto yy50;
	}
yy395:
	yyaccept = 53;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy396;
	}
yy396:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::AFTER }; }
yy397:
	yyaccept = 54;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy398;
	}
yy398:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ALIAS }; }
yy399:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy462;
	default: goto yy50;
	}
yy400:
	yyaccept = 55;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy401;
	}
yy401:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ARRAY }; }
yy402:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy463;
	default: goto yy50;
	}
yy403:
	yyaccept = 56;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy404;
	}
yy404:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::BEGIN }; }
yy405:
	yyaccept = 57;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy406;
	}
yy406:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::BLOCK }; }
yy407:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy465;
	default: goto yy50;
	}
yy408:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy467;
	default: goto yy50;
	}
yy409:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'G':
	case 'g': goto yy468;
	default: goto yy50;
	}
yy410:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy469;
	default: goto yy50;
	}
yy411:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy470;
	default: goto yy50;
	}
yy412:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy471;
	default: goto yy50;
	}
yy413:
	yyaccept = 58;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy414;
	}
yy414:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ELSIF }; }
yy415:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'Y':
	case 'y': goto yy473;
	default: goto yy50;
	}
yy416:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy475;
	default: goto yy50;
	}
yy417:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy476;
	case 'I':
	case 'i': goto yy477;
	default: goto yy50;
	}
yy418:
	yyaccept = 59;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy419;
	}
yy419:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::GROUP }; }
yy420:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy478;
	default: goto yy50;
	}
yy421:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy479;
	default: goto yy50;
	}
yy422:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy481;
	default: goto yy50;
	}
yy423:
	yyaccept = 60;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy424;
	}
yy424:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::INOUT }; }
yy425:
	yyaccept = 61;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy426;
	}
yy426:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::LABEL }; }
yy427:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy482;
	default: goto yy50;
	}
yy428:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'G':
	case 'g': goto yy483;
	default: goto yy50;
	}
yy429:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy484;
	default: goto yy50;
	}
yy430:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy485;
	default: goto yy50;
	}
yy431:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'G':
	case 'g': goto yy487;
	default: goto yy50;
	}
yy432:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy488;
	default: goto yy50;
	}
yy433:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy489;
	case 'S':
	case 's': goto yy490;
	default: goto yy50;
	}
yy434:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy491;
	default: goto yy50;
	}
yy435:
	yyaccept = 62;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy436;
	}
yy436:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::RANGE }; }
yy437:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy492;
	default: goto yy50;
	}
yy438:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy494;
	default: goto yy50;
	}
yy439:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy495;
	default: goto yy50;
	}
yy440:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy496;
	default: goto yy50;
	}
yy441:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy498;
	default: goto yy50;
	}
yy442:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy500;
	default: goto yy50;
	}
yy443:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy502;
	default: goto yy50;
	}
yy444:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy504;
	default: goto yy50;
	}
yy445:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy505;
	default: goto yy50;
	}
yy446:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy507;
	default: goto yy50;
	}
yy447:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'P':
	case 'p': goto yy509;
	default: goto yy50;
	}
yy448:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'P':
	case 'p': goto yy510;
	default: goto yy50;
	}
yy449:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy511;
	default: goto yy50;
	}
yy450:
	yyaccept = 63;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy451;
	}
yy451:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::UNITS }; }
yy452:
	yyaccept = 64;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy453;
	}
yy453:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::UNTIL }; }
yy454:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'B':
	case 'b': goto yy512;
	default: goto yy50;
	}
yy455:
	yyaccept = 65;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy456;
	}
yy456:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::WHILE }; }
yy457:
	++cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9': goto yy458;
	default: goto yy73;
	}
yy458:
	yyaccept = 34;
	++cursor;
	marker = cursor;
	if (limit - cursor < 1) true;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9': goto yy458;
	case '_': goto yy457;
	default: goto yy302;
	}
yy460:
	yyaccept = 66;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy461;
	}
yy461:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ACCESS }; }
yy462:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy513;
	default: goto yy50;
	}
yy463:
	yyaccept = 67;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy464;
	}
yy464:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ASSERT }; }
yy465:
	yyaccept = 68;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy466;
	}
yy466:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::BUFFER }; }
yy467:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy514;
	default: goto yy50;
	}
yy468:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'U':
	case 'u': goto yy515;
	default: goto yy50;
	}
yy469:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy516;
	default: goto yy50;
	}
yy470:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy517;
	default: goto yy50;
	}
yy471:
	yyaccept = 69;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy472;
	}
yy472:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::DOWNTO }; }
yy473:
	yyaccept = 70;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy474;
	}
yy474:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ENTITY }; }
yy475:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy518;
	default: goto yy50;
	}
yy476:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy519;
	default: goto yy50;
	}
yy477:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy520;
	default: goto yy50;
	}
yy478:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy522;
	default: goto yy50;
	}
yy479:
	yyaccept = 71;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy480;
	}
yy480:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::IMPURE }; }
yy481:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy524;
	default: goto yy50;
	}
yy482:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'Y':
	case 'y': goto yy525;
	default: goto yy50;
	}
yy483:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy527;
	default: goto yy50;
	}
yy484:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy529;
	default: goto yy50;
	}
yy485:
	yyaccept = 72;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy486;
	}
yy486:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::OTHERS }; }
yy487:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy531;
	default: goto yy50;
	}
yy488:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy533;
	default: goto yy50;
	}
yy489:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'U':
	case 'u': goto yy534;
	default: goto yy50;
	}
yy490:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'S':
	case 's': goto yy535;
	default: goto yy50;
	}
yy491:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy537;
	default: goto yy50;
	}
yy492:
	yyaccept = 73;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy493;
	}
yy493:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::RECORD }; }
yy494:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy538;
	default: goto yy50;
	}
yy495:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy539;
	default: goto yy50;
	}
yy496:
	yyaccept = 74;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy497;
	}
yy497:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::REJECT }; }
yy498:
	yyaccept = 75;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy499;
	}
yy499:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::REPORT }; }
yy500:
	yyaccept = 76;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy501;
	}
yy501:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::RETURN }; }
yy502:
	yyaccept = 77;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy503;
	}
yy503:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::SELECT }; }
yy504:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy540;
	default: goto yy50;
	}
yy505:
	yyaccept = 78;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy506;
	}
yy506:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::SHARED }; }
yy507:
	yyaccept = 79;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy508;
	}
yy508:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::SIGNAL }; }
yy509:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy541;
	default: goto yy50;
	}
yy510:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy543;
	default: goto yy50;
	}
yy511:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy544;
	default: goto yy50;
	}
yy512:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy545;
	default: goto yy50;
	}
yy513:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy546;
	default: goto yy50;
	}
yy514:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy547;
	default: goto yy50;
	}
yy515:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy548;
	default: goto yy50;
	}
yy516:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy549;
	default: goto yy50;
	}
yy517:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy551;
	default: goto yy50;
	}
yy518:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy552;
	default: goto yy50;
	}
yy519:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy554;
	default: goto yy50;
	}
yy520:
	yyaccept = 80;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy521;
	}
yy521:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::GENERIC }; }
yy522:
	yyaccept = 81;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy523;
	}
yy523:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::GUARDED }; }
yy524:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy556;
	default: goto yy50;
	}
yy525:
	yyaccept = 82;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy526;
	}
yy526:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::LIBRARY }; }
yy527:
	yyaccept = 83;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy528;
	}
yy528:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::LINKAGE }; }
yy529:
	yyaccept = 84;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy530;
	}
yy530:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::LITERAL }; }
yy531:
	yyaccept = 85;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy532;
	}
yy532:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::PACKAGE }; }
yy533:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy558;
	default: goto yy50;
	}
yy534:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy559;
	default: goto yy50;
	}
yy535:
	yyaccept = 86;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy536;
	}
yy536:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::PROCESS }; }
yy537:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy560;
	default: goto yy50;
	}
yy538:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy561;
	default: goto yy50;
	}
yy539:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy562;
	default: goto yy50;
	}
yy540:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'Y':
	case 'y': goto yy564;
	default: goto yy50;
	}
yy541:
	yyaccept = 87;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy542;
	}
yy542:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::SUBTYPE }; }
yy543:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy566;
	default: goto yy50;
	}
yy544:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy567;
	default: goto yy50;
	}
yy545:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy568;
	default: goto yy50;
	}
yy546:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy570;
	default: goto yy50;
	}
yy547:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy571;
	default: goto yy50;
	}
yy548:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy573;
	default: goto yy50;
	}
yy549:
	yyaccept = 88;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy550;
	}
yy550:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::CONSTANT }; }
yy551:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'C':
	case 'c': goto yy574;
	default: goto yy50;
	}
yy552:
	yyaccept = 89;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy553;
	}
yy553:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::FUNCTION }; }
yy554:
	yyaccept = 90;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy555;
	}
yy555:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::GENERATE }; }
yy556:
	yyaccept = 91;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy557;
	}
yy557:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::INERTIAL }; }
yy558:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy575;
	default: goto yy50;
	}
yy559:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'A':
	case 'a': goto yy577;
	case 'E':
	case 'e': goto yy578;
	default: goto yy50;
	}
yy560:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy580;
	default: goto yy50;
	}
yy561:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy582;
	default: goto yy50;
	}
yy562:
	yyaccept = 92;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy563;
	}
yy563:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::REGISTER }; }
yy564:
	yyaccept = 93;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy565;
	}
yy565:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::SEVERITY }; }
yy566:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy584;
	default: goto yy50;
	}
yy567:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy586;
	default: goto yy50;
	}
yy568:
	yyaccept = 94;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy569;
	}
yy569:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::VARIABLE }; }
yy570:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'U':
	case 'u': goto yy587;
	default: goto yy50;
	}
yy571:
	yyaccept = 95;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy572;
	}
yy572:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::COMPONENT }; }
yy573:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy588;
	default: goto yy50;
	}
yy574:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'T':
	case 't': goto yy589;
	default: goto yy50;
	}
yy575:
	yyaccept = 96;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy576;
	}
yy576:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::POSTPONED }; }
yy577:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'L':
	case 'l': goto yy591;
	default: goto yy50;
	}
yy578:
	yyaccept = 97;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy579;
	}
yy579:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::PROCEDURE }; }
yy580:
	yyaccept = 98;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy581;
	}
yy581:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::PROTECTED }; }
yy582:
	yyaccept = 99;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy583;
	}
yy583:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::REFERENCE }; }
yy584:
	yyaccept = 100;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy585;
	}
yy585:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::TRANSPORT }; }
yy586:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'D':
	case 'd': goto yy593;
	default: goto yy50;
	}
yy587:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'R':
	case 'r': goto yy595;
	default: goto yy50;
	}
yy588:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'I':
	case 'i': goto yy596;
	default: goto yy50;
	}
yy589:
	yyaccept = 101;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy590;
	}
yy590:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::DISCONNECT }; }
yy591:
	yyaccept = 102;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy592;
	}
yy592:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::PROCEDURAL }; }
yy593:
	yyaccept = 103;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy594;
	}
yy594:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::UNAFFECTED }; }
yy595:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'E':
	case 'e': goto yy597;
	default: goto yy50;
	}
yy596:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'O':
	case 'o': goto yy599;
	default: goto yy50;
	}
yy597:
	yyaccept = 104;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy598;
	}
yy598:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::ARCHITECTURE }; }
yy599:
	yyaccept = 3;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case 'N':
	case 'n': goto yy600;
	default: goto yy50;
	}
yy600:
	yyaccept = 105;
	++cursor;
	marker = cursor;
	yych = *cursor;
	switch (yych) {
	case '0' ... '9':
	case 'A' ... 'Z':
	case 'a' ... 'z': goto yy49;
	case '_': goto yy106;
	default: goto yy601;
	}
yy601:
	{ return ReservedWord { begin_offset, std::string_view { begin_cursor, cursor - begin_cursor }, ReservedWordKind::CONFIGURATION }; }
}

    }
}

} // namespace Lexer